global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "Ika-Validator"
    static_configs:
      - targets: ["${IKA_METRICS_TARGET}"]
        labels:
          group: 'IkaValidator'
          network: 'testnet'
    metrics_path: '/metrics' 
    
  - job_name: "Sui-Fullnode"
    static_configs:
      - targets: ["${SUI_METRICS_TARGET}"]
        labels:
          group: 'Fullnode'
          network: 'testnet' 
    metrics_path: '/metrics' 